# Generated by Django 4.2.15 on 2024-08-09 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roar_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="active_category_unit", old_name="active_id", new_name="active",
        ),
    ]
