# Generated by Django 4.2.15 on 2024-08-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roar_api", "0002_rename_active_id_active_category_unit_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="active_information",
            name="is_deleted",
            field=models.BooleanField(default=True),
        ),
    ]
