# Generated by Django 5.1 on 2024-08-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roar_api', '0003_active_information_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_information',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
