# Generated by Django 5.1 on 2024-08-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roar_api', '0004_alter_active_information_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_information',
            name='discount_info',
            field=models.CharField(max_length=1000),
        ),
    ]
