# Generated by Django 5.1 on 2024-08-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roar_api', '0005_alter_active_information_discount_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_category_unit',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='active_show_information',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
    ]
